server:
  port: 9011

dubbo:
  application:
    name: dubbo-web
  registry:
    address: zookeeper://123.56.16.67:2181
    protocol: zookeeper
    check: true
  consumer:
    check:  true
    timeout: 3000
