server:
  port: 9010

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.16.67:3306/wetools?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 111111

mybatis:
  mapper-locations: classpath:mapper/*.xml

dubbo:
  application:
    name: dubbo-server
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://123.56.16.67:2181
    protocol: zookeeper
    check: false
  provider:
    check: false
    timeout: 3000



