server:
  port: 9012

dubbo:
  application:
    name: dubbo-spider
  registry:
    address: zookeeper://123.56.16.67:2181
    protocol: zookeeper
    check: false
  consumer:
    check:  false
    timeout: 3000
